tasks:
  enable_multilib:
    pacman_conf: /etc/pacman.conf
  bootstrap_aur:
    aur_helper: yay
    aur_helper_package: yay
  install_pkg:
    source: packages.yml
    aur_helper: yay
  copy_dotfile:
    source_dir: dotfiles
    dest_dir: "~"
  enable_service:
    services:
      - docker
      - tailscaled
      - ollama
  add_user_to_group:
    groups:
      - docker
