#!/bin/bash -e

if test ! "$(which python)"; then
  echo "Python not found, installing..."

  sudo pacman -S python
fi

if test ! "$(which yay)"; then
  echo "Yay not found, installing..."

  git clone https://aur.archlinux.org/yay.git /tmp/yay
  cd /tmp/yay
  makepkg -si
fi

if test ! "$(which ansible)"; then
  echo "Ansible not found, installing..."
  sudo pacman -S ansible
fi

ansible_plugin_path=$HOME/.ansible/plugins/modules
if test ! -f "$ansible_plugin_path/yay"; then
  echo "Ansible Yay not found, installing..."

  curl -fLo "$ansible_plugin_path/yay" --create-dirs \
    https://raw.githubusercontent.com/mnussbaum/ansible-yay/master/yay
fi

python --version
ansible --version
ansible-playbook -K ansible/main.yml
