- name: Install Vim
  become: yes
  pacman: name=vim

- name: Install vim-plug
  shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: ~/.vim/autoload/plug.vim

- name: Install vim plugins
  shell: vim -c PlugInstall -c q -c q
