- name: Install Xorg and tools
  become: yes
  pacman:
    name:
      - xf86-input-libinput
      - xorg-server
      - xorg-xinit
      - xorg-xinput
      - xorg-xprop
      - xorg-xwininfo
      - xorg-xrandr

- name: Install i3
  become: yes
  pacman: name=i3-wm

- name: Install status bar
  yay: name=polybar

- name: Install screen utilities
  become: yes
  pacman:
    name:
      - arandr
      - feh
      - i3lock
      - scrot

- name: Install PCMan
  become: yes
  pacman: name=pcmanfm-gtk3

- name: Install ranger
  become: yes
  pacman: name=ranger

- name: Install Rofi
  become: yes
  pacman: name=rofi