- name: Install Erlang
  become: yes
  pacman: name=erlang

- name: Install Elixir
  become: yes
  pacman: name=elixir

# - name: Install Clojure
#   become: yes
#   pacman: name=clojure

# - name: Install Leiningen (Clojure)
#   yay: name=leiningen

- name: Install GO
  become: yes
  pacman: name=go

# - name: Install Node, NPM, and Yarn
#   become: yes
#   pacman:
#     name:
#       - nodejs
#       - npm
#       - yarn
