- name: Install common tools
  become: yes
  pacman:
    name:
      - yq

- name: Install Python PIP
  become: yes
  pacman: name=python-pip

- name: Install Docker and Docker-Compose
  become: yes
  pacman:
    name:
      - docker
      - docker-compose

- name: Enable Docker Daemon
  become: yes
  systemd: name=docker enabled=yes state=started

- name: Install Kubernetes Tools
  become: yes
  pacman: name=kubectl

- name: Install Postman
  yay: name=postman

- name: Install PostgreSQL client and libs
  become: yes
  pacman: name=postgresql-libs

- name: Install Dbeaver
  become: yes
  pacman: name=dbeaver
